rewrite anti overwrite check

diff --git a/hooks/push b/hooks/push
--- a/hooks/push
+++ b/hooks/push
@@ -10,22 +10,25 @@ DOCKER_IMAGE="${DOCKER_REPO:-smtp-relay}"
 set -e
 
 image_version=`cat VERSION`
+image_name=`cat ${PWD}/_image`
 image_tags=`cat ${PWD}/_tags`
+image_building_name=`cat ${PWD}/_image_build`
 
 
 ## Enforce versioning
-if curl -s 'https://hub.docker.com/v2/repositories/turgon37/smtp-relay/tags/?page_size=100' | grep -q '"name": "'${image_version}'"'; then
-  echo "ERROR: Tag for image version '$image_version' already exists in registry"
-  exit 1
-fi
-
+for tag in $image_tags; do
+  if echo "$tag" | grep -q "$image_version"; then
+    if curl -s 'https://hub.docker.com/v2/repositories/turgon37/smtp-relay/tags/?page_size=100' | grep -q '"name": "'${tag}'"'; then
+      echo "ERROR: Tag '${tag}' for image version '$image_version' already exists in registry"
+      exit 1
+    fi
+  fi
+done
 
 ## Push images
 for tag in $image_tags; do
-  echo "=> tag image '${DOCKER_IMAGE}:building' as '${DOCKER_IMAGE}:${tag}'"
-  docker tag "${DOCKER_IMAGE}:building" "${DOCKER_IMAGE}:${tag}"
-  echo "=> push image '${DOCKER_IMAGE}:${tag}'"
-  docker push "${DOCKER_IMAGE}:${tag}"
+  echo "=> tag image '${image_building_name}' as '${image_name}:${tag}'"
+  docker tag "${image_building_name}" "${image_name}:${tag}"
+  echo "=> push image '${image_name}:${tag}'"
+  docker push "${image_name}:${tag}"
 done
-
-
