Extract username and repo from env

diff --git a/hooks/push b/hooks/push
--- a/hooks/push
+++ b/hooks/push
@@ -9,8 +9,15 @@ DOCKER_IMAGE="${DOCKER_REPO:-smtp-relay}"
 ## Initialization
 set -e
 
+if [[ ${DOCKER_REPO} =~ [^/]+/([^/]+)/([^/]+) ]]; then
+  username=${BASH_REMATCH[1]}
+  repo=${BASH_REMATCH[2]}
+else
+  echo 'ERROR: unable to extract username and repo from environment' 1>&2
+  exit 1
+fi
+
 image_version=`cat VERSION`
-image_name=`cat ${PWD}/_image`
 image_tags=`cat ${PWD}/_tags`
 image_building_name=`cat ${PWD}/_image_build`
 
@@ -18,8 +25,8 @@ image_building_name=`cat ${PWD}/_image_build`
 ## Enforce versioning
 for tag in $image_tags; do
   if echo "$tag" | grep -q "$image_version"; then
-    if curl -s 'https://hub.docker.com/v2/repositories/turgon37/smtp-relay/tags/?page_size=100' | grep -q '"name": "'${tag}'"'; then
-      echo "ERROR: Tag '${tag}' for image version '$image_version' already exists in registry"
+    if curl -s "https://hub.docker.com/v2/repositories/${username}/${repo}/tags/?page_size=100" | grep -q '"name": "'${tag}'"'; then
+      echo "ERROR: Tag '${tag}' for image version '$image_version' already exists in registry" 1>&2
       exit 1
     fi
   fi
@@ -27,8 +34,8 @@ done
 
 ## Push images
 for tag in $image_tags; do
-  echo "=> tag image '${image_building_name}' as '${image_name}:${tag}'"
-  docker tag "${image_building_name}" "${image_name}:${tag}"
-  echo "=> push image '${image_name}:${tag}'"
-  docker push "${image_name}:${tag}"
+  echo "=> tag image '${image_building_name}' as '${DOCKER_IMAGE}:${tag}'"
+  docker tag "${image_building_name}" "${DOCKER_IMAGE}:${tag}"
+  echo "=> push image '${DOCKER_IMAGE}:${tag}'"
+  docker push "${DOCKER_IMAGE}:${tag}"
 done
